global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'flights'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'flights:8080' ]
  - job_name: 'hotels'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'hotels:8090' ]
  - job_name: 'gatewayserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8072' ]
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8071' ]
  
