encrypt:
  key: fabrix
server:
  port: 8071
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          default-label: main
          uri: https://github.com/fabrizio1987/microservices-config.git
  profiles:
    active: git

management:
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      fabrix: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"     
     